language: ja-JP
reviews:
  auto_review: true
  review_status: true
  poem: false
  collapse_walkthrough: false
  # Enable reviews for all branches, not just the default branch
  base_branches:
    - "**"
chat:
  auto_reply: true
